const functions = require("firebase-functions");
const admin = require("firebase-admin");
const fs = require("fs");
const path = require("path");

admin.initializeApp();

const db = admin.firestore();

exports.app = functions.https.onRequest(async (req, res) => {
    const userAgent = req.headers["user-agent"] || "";
    const isBot = /facebookexternalhit|twitterbot|linkedinbot|whatsapp|telegram|slackbot/i.test(userAgent);

    // If it's not a bot, we could just serve the static file, but for simplicity/consistency
    // and to support "copy link" previews which might be generated by the browser or OS services,
    // we'll serve the dynamic content. However, for performance, we might want to just serve static for normal users.
    // For now, let's serve dynamic for everyone to ensure the tags are always right.

    const menuId = req.query.menu;
    const vehicleId = req.query.vehicle;

    let title = "Meny Cars | Catálogo Digital Premium";
    let description = "Descubre nuestra selección exclusiva de vehículos. Financiación a medida y las mejores oportunidades del mercado.";
    let imageUrl = "https://copiloto-crm-1764216245.web.app/assets/chatbot_avatar.png";
    let url = "https://copiloto-crm-1764216245.web.app/";

    try {
        if (vehicleId) {
            const vehicleDoc = await db.collection("vehicles").doc(vehicleId).get();
            if (vehicleDoc.exists) {
                const vehicle = vehicleDoc.data();
                title = `${vehicle.make} ${vehicle.model} ${vehicle.year} | Meny Cars`;
                description = `Precio: $${vehicle.price.toLocaleString()} - ${vehicle.mileage.toLocaleString()} km. ${vehicle.description || ''}`;
                if (vehicle.imageUrls && vehicle.imageUrls.length > 0) {
                    imageUrl = vehicle.imageUrls[0];
                }
                url = `https://copiloto-crm-1764216245.web.app/?vehicle=${vehicleId}`;
            }
        } else if (menuId) {
            const menuDoc = await db.collection("menus").doc(menuId).get();
            if (menuDoc.exists) {
                const menu = menuDoc.data();
                title = `${menu.name || 'Catálogo Personalizado'} | Meny Cars`;

                // Try to get the first vehicle image
                if (menu.vehicleIds && menu.vehicleIds.length > 0) {
                    const firstVehicleId = menu.vehicleIds[0];
                    const vehicleDoc = await db.collection("vehicles").doc(firstVehicleId).get();
                    if (vehicleDoc.exists) {
                        const vehicle = vehicleDoc.data();
                        if (vehicle.imageUrls && vehicle.imageUrls.length > 0) {
                            imageUrl = vehicle.imageUrls[0];
                        }
                    }
                }
                url = `https://copiloto-crm-1764216245.web.app/?menu=${menuId}`;
            }
        }
    } catch (error) {
        console.error("Error fetching data for OG tags:", error);
    }

    // Read index.html
    // Note: In production, index.html is in the 'dist' folder (or wherever hosting points to).
    // When deployed, functions are separate. We need to ensure index.html is accessible.
    // A common pattern is to copy index.html to the functions folder during build, 
    // OR just embed the template string if it's simple.
    // Since we have a build process, let's try to read it from the deployed hosting files if possible,
    // but functions run in a different environment.
    // SAFEST APPROACH: Embed the HTML template or copy it.
    // Let's assume we will copy dist/index.html to functions/index.html before deploy.

    const indexHtmlPath = path.join(__dirname, "index.html");
    let html = fs.readFileSync(indexHtmlPath, "utf8");

    // Replace Meta Tags
    html = html.replace(/<meta property="og:title" content="[^"]+" \/>/g, `<meta property="og:title" content="${title}" />`);
    html = html.replace(/<meta property="og:description" content="[^"]+" \/>/g, `<meta property="og:description" content="${description}" />`);
    html = html.replace(/<meta property="og:image" content="[^"]+" \/>/g, `<meta property="og:image" content="${imageUrl}" />`);
    html = html.replace(/<meta property="og:url" content="[^"]+" \/>/g, `<meta property="og:url" content="${url}" />`);

    html = html.replace(/<meta property="twitter:title" content="[^"]+" \/>/g, `<meta property="twitter:title" content="${title}" />`);
    html = html.replace(/<meta property="twitter:description" content="[^"]+" \/>/g, `<meta property="twitter:description" content="${description}" />`);
    html = html.replace(/<meta property="twitter:image" content="[^"]+" \/>/g, `<meta property="twitter:image" content="${imageUrl}" />`);
    html = html.replace(/<meta property="twitter:url" content="[^"]+" \/>/g, `<meta property="twitter:url" content="${url}" />`);

    // Also update standard title
    html = html.replace(/<title>[^<]+<\/title>/g, `<title>${title}</title>`);

    res.set("Cache-Control", "public, max-age=300, s-maxage=600");
    res.send(html);
});
